version: '3.4'

services:
  devblog.api:
    image: ${DOCKER_REGISTRY-}devblogapi
    build:
      context: .
      dockerfile: src/DevBlog.Api/Dockerfile
    ports:
      - "7004:7004"
    environment:
      - ASPNETCORE_URLS=http://*:7004
    depends_on: [mssql, seq_logs]
    networks:
      - app-network
  devblog.webapp:
    image: ${DOCKER_REGISTRY-}devblogwebapp
    build:
      context: .
      dockerfile: src/DevBlog.WebApp/Dockerfile
    ports:
      - "7139:7139"
    environment:
      - ASPNETCORE_URLS=http://*:7139
    depends_on:
      - devblog.api
    networks:
      - app-network
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql_server
    hostname: mssql
    environment:
     - MSSQL_SA_PASSWORD=P@ssword1
     - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
     - "1401:1433"
    networks:
      - app-network 
  seq_logs:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
       